name: 🔄 Compatibility request 
description: File a compatibility request
labels: ["compatibility", "medium priority"]
assignees: ["Crystal-Spider"]
body:
- type: checkboxes
  attributes:
    label: I have confirmed no other issue asks for this
    description: Please search if an issue already exists for the compatibility you wish for.
    options:
    - label: I have searched for existing issues
      required: true
- type: input
  attributes:
    label: Other mod
    description: |
      Other mod you wish to be compatible.
  validations:
    required: true
- type: textarea
  attributes:
    label: Current behavior
    description: A concise description of the current behavior.
  validations:
    required: true
- type: textarea
  attributes:
    label: Desired behavior
    description: A concise description of what you'd like to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Stacktrace and logs
    description: |
      Optionally paste here a link to [pastebin](https://pastebin.com/) with the crash-report/log.
    placeholder: |
      Under your Minecraft instance folder:
      
      - The crash-report is located in the "crash-reports" folder.
      - The latest log is located in the "logs" folder under.
- type: textarea
  attributes:
    label: Additional context
    description: |
      Insert here anything that will give us more context about the compatibility you wish for.
