name: 📚 Documentation enhancement 
description: File a documentation enhancement
labels: ["documentation", "medium priority"]
assignees: ["Crystal-Spider"]
body:
- type: checkboxes
  attributes:
    label: I have confirmed no other issue asks for this
    description: Please search if an issue already exists for the same documentation enhancement.
    options:
    - label: I have searched for existing issues
      required: true
- type: input
  attributes:
    label: What needs an update
    description: |
      Which documentation needs an update.
    placeholder: |
      E.g. readme, wiki, website...
  validations:
    required: true
- type: textarea
  attributes:
    label: Current documentation content
    description: Specify the section(s) you'd like to change.
  validations:
    required: true
- type: textarea
  attributes:
    label: Change reason
    description: A concise explanation of why the documentation should change.
  validations:
    required: true
- type: textarea
  attributes:
    label: Desired changes
    description: Optionally suggest the changes you'd like. 
- type: textarea
  attributes:
    label: Additional context
    description: |
      Insert here anything that will give us more context.
